import { Artisan, Product, Order, ChatMessage, Conversation, AppNotification } from '../types';

export const INITIAL_ARTISANS: Artisan[] = [
  {
    id: "artisan-1",
    name: "Rameshwar Kumbhar",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
    coverImage: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1200&q=80",
    bio: "5th generation master terracotta craftsman from Panchmura, Bishnupur. Preserving ancient Bengal temple terracotta motifs and clay firing arts without chemical additives.",
    village: "Panchmura Village, Bishnupur",
    region: "Bankura District",
    state: "West Bengal",
    pincode: "722202",
    craftSpecialty: "Terracotta & Bankura Horse Craft",
    experienceYears: 34,
    community: "Kumbhakar Artisan Guild",
    verified: true,
    phone: "+91 98321 44521",
    email: "rameshwar.kumbhar@karigar.in",
    rating: 4.9,
    totalSales: 218,
    totalEarnings: 312000,
    monthlySales: 24,
    craftLineage: "Family tradition active since 1882. Winner of State Master Craftsman Merit.",
    materials: ["Alluvial Riverbed Clay", "Natural Red Oxide Slip", "Wood Ash Glaze", "Wild Straw Temper"],
    techniques: ["Wheel Throwing", "Traditional Hand Pinching", "Wood-Fired Updraft Kiln Firing"],
    workshopPhotos: [
      "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=600&q=80",
      "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=600&q=80",
    ],
    audioBioText: "Namaskar, my name is Rameshwar. My hands have shaped river clay since I was seven years old. Every piece is baked in wood-fired earthen kilns, bringing the sacred soil of Bengal into your home.",
    verification: {
      status: "verified",
      verificationId: "KARIGAR-VERIFIED-WB-1882",
      pehchanArtisanId: "PA-WB-BK-2021-9941",
      govIdType: "pehchan_card",
      govIdNumberMasked: "•••• •••• 9941",
      giCertificationCluster: "Bankura Terracotta (GI Application No. 128)",
      clusterAffiliation: "Bishnupur Rural Artisan Cluster Society",
      verifiedDate: "2024-03-15",
      verifierBadge: "National Craft Council Verified",
      authenticityScore: 99,
      fairWageScore: 100,
      giClusterScore: 98,
      badges: [
        "Pehchan Ministry Recognized",
        "GI-Tag Cluster Certified",
        "100% Direct Fair Wage Escrow",
        "5th Gen Heritage Lineage",
        "Zero-Chemical Eco Clay"
      ],
      bankDetails: {
        accountHolder: "Rameshwar Kumbhar",
        bankName: "State Bank of India (Bishnupur Branch)",
        accountNumberMasked: "••••••••4892",
        ifscCode: "SBIN0000045",
        upiVpa: "rameshwar.kumbhar@oksbi"
      },
      workshopProofImages: [
        "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=600&q=80"
      ],
      sampleCraftImages: [
        "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=600&q=80"
      ],
      reviewerNotes: "Physical kiln audit conducted by Bengal Craft Directorate. Natural alluvial clay source certified 100% authentic."
    }
  },
  {
    id: "artisan-2",
    name: "Mangala Devi Jhala",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80",
    coverImage: "https://images.unsplash.com/photo-1606744824163-985d376605aa?auto=format&fit=crop&w=1200&q=80",
    bio: "Tribal women empowerment leader and master Dhokra metal artisan. Specializes in 4,000-year-old non-ferrous lost-wax casting practiced by indigenous Bastar tribes.",
    village: "Kondagaon Tribal Settlement",
    region: "Bastar",
    state: "Chhattisgarh",
    pincode: "494226",
    craftSpecialty: "Dokra Lost-Wax Bell Metal Casting",
    experienceYears: 26,
    community: "Bastar Tribal Artisans Collective",
    verified: true,
    phone: "+91 94255 88120",
    email: "mangala.dhokra@karigar.in",
    rating: 4.8,
    totalSales: 164,
    totalEarnings: 384000,
    monthlySales: 19,
    craftLineage: "Ghadwa tribe lost-wax technique utilizing beeswax thread spirals and alluvial river clay molds.",
    materials: ["Recycled Bell Metal & Brass", "Forest Beeswax", "River Clay Core", "Rice Husk Ash"],
    techniques: ["Cire Perdue (Lost-Wax)", "Hand Coiling Beeswax Filigree", "Pit Crucible Smelting"],
    workshopPhotos: [
      "https://images.unsplash.com/photo-1606744824163-985d376605aa?auto=format&fit=crop&w=600&q=80",
    ],
    audioBioText: "Johar! In Dokra, no two pieces are ever identical. The wax model melts away in the fire, leaving behind a unique soul of pure brass and tribal memory.",
    verification: {
      status: "verified",
      verificationId: "KARIGAR-VERIFIED-CG-4011",
      pehchanArtisanId: "PA-CG-BS-2022-3810",
      govIdType: "pehchan_card",
      govIdNumberMasked: "•••• •••• 3810",
      giCertificationCluster: "Bastar Dhokra (GI Application No. 83)",
      clusterAffiliation: "Saathi Bastar Tribal Federation",
      verifiedDate: "2024-04-10",
      verifierBadge: "TRIFED & Ministry of Textiles Certified",
      authenticityScore: 98,
      fairWageScore: 100,
      giClusterScore: 99,
      badges: [
        "TRIFED Tribal Certified",
        "GI-Tag Bastar Dhokra",
        "Women Collective Head",
        "100% Lost-Wax Cast"
      ],
      bankDetails: {
        accountHolder: "Mangala Devi Jhala",
        bankName: "Chhattisgarh Rajya Gramin Bank",
        accountNumberMasked: "••••••••1109",
        ifscCode: "CRGB0001042",
        upiVpa: "mangala.jhala@icici"
      },
      workshopProofImages: [
        "https://images.unsplash.com/photo-1606744824163-985d376605aa?auto=format&fit=crop&w=600&q=80"
      ],
      sampleCraftImages: [
        "https://images.unsplash.com/photo-1590736969955-71cc94801759?auto=format&fit=crop&w=600&q=80"
      ]
    }
  },
  {
    id: "artisan-3",
    name: "Sunita & Radhey Mohan",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    coverImage: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=80",
    bio: "Madhubani folk painters using hand-ground natural dyes extracted from turmeric, indigo, crushed marigold flowers, and cow dung washes on handmade recycled cotton sheets.",
    village: "Ranti Village, Madhubani",
    region: "Mithila Region",
    state: "Bihar",
    pincode: "847211",
    craftSpecialty: "Kachni & Bharni Madhubani Painting",
    experienceYears: 21,
    community: "Mithila Mahila Kalakar Parishad",
    verified: true,
    phone: "+91 99312 77402",
    email: "sunita.mithila@karigar.in",
    rating: 4.95,
    totalSales: 310,
    totalEarnings: 512000,
    monthlySales: 32,
    craftLineage: "Generational wedding and harvest ritual wall art translated onto archival museum fabrics.",
    materials: ["Handmade Cotton Paper", "Wild Indigo", "Turmeric Pigment", "Soot Lampblack", "Banyan Milk"],
    techniques: ["Fine Bamboo Nib Pen Line Drawing (Kachni)", "Solid Color Fill (Bharni)", "Natural Mordanting"],
    workshopPhotos: [
      "https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=600&q=80",
    ],
    audioBioText: "Our colors come from the sun, the soil, and wild forest leaves. Madhubani represents the harmony between women, birds, and cosmic nature.",
    verification: {
      status: "verified",
      verificationId: "KARIGAR-VERIFIED-BR-1904",
      pehchanArtisanId: "PA-BR-MB-2020-5572",
      govIdType: "pehchan_card",
      govIdNumberMasked: "•••• •••• 5572",
      giCertificationCluster: "Madhubani Paintings (GI Application No. 105)",
      clusterAffiliation: "Mithila Folk Art Guild",
      verifiedDate: "2024-02-18",
      verifierBadge: "Bihar State Crafts Council Verified",
      authenticityScore: 97,
      fairWageScore: 100,
      giClusterScore: 96,
      badges: [
        "GI-Tag Mithila Certified",
        "Pehchan Card Verified",
        "100% Botanical Pigments",
        "Direct Artisan Escrow"
      ],
      bankDetails: {
        accountHolder: "Sunita Devi Mohan",
        bankName: "Punjab National Bank",
        accountNumberMasked: "••••••••7821",
        ifscCode: "PUNB0128400",
        upiVpa: "sunita.mithila@okaxis"
      }
    }
  },
  {
    id: "artisan-4",
    name: "Kalyan Weavers Cooperative",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    coverImage: "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&w=1200&q=80",
    bio: "Traditional pit-loom master weavers dedicated to rare natural-dyed Ikat and organic mulberry handloom silks with zero synthetic filaments.",
    village: "Bhoodan Pochampally",
    region: "Yadadri District",
    state: "Telangana",
    pincode: "508284",
    craftSpecialty: "Double Ikat Silk & Cotton Weaving",
    experienceYears: 40,
    community: "Telangana Padmashali Handloom Guild",
    verified: true,
    phone: "+91 97001 22910",
    email: "kalyan.pochampally@karigar.in",
    rating: 4.9,
    totalSales: 142,
    totalEarnings: 689000,
    monthlySales: 15,
    craftLineage: "GI-Tag certified geometric double ikat precision mapping across 600 warp and weft threads.",
    materials: ["Pure Mulberry Silk", "Desi Organic Cotton", "Natural Madder & Indigo Dyes", "Pure Zari"],
    techniques: ["Precision Resist Tie-Dye", "Traditional Pit Loom Weaving", "Shuttle Handloom"],
    workshopPhotos: [
      "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&w=600&q=80",
    ],
    audioBioText: "Each saree takes up to three weeks of warp tying and mathematical dyeing before the shuttle ever moves across the loom.",
    verification: {
      status: "verified",
      verificationId: "KARIGAR-VERIFIED-TS-6029",
      pehchanArtisanId: "PA-TS-PC-2019-1120",
      govIdType: "pehchan_card",
      govIdNumberMasked: "•••• •••• 1120",
      giCertificationCluster: "Pochampally Ikat (GI Application No. 4)",
      clusterAffiliation: "Pochampally Handloom Weavers Cooperative",
      verifiedDate: "2024-01-20",
      verifierBadge: "Handloom Mark & Silk Mark Certified",
      authenticityScore: 100,
      fairWageScore: 100,
      giClusterScore: 100,
      badges: [
        "Handloom Mark Certified",
        "Silk Mark Certified",
        "GI-Tag Pochampally Ikat",
        "Direct Cooperative Payout"
      ],
      bankDetails: {
        accountHolder: "Kalyan Weavers Society",
        bankName: "Canara Bank (Pochampally)",
        accountNumberMasked: "••••••••3490",
        ifscCode: "CNRB0002154",
        upiVpa: "kalyan.weavers@canarabank"
      }
    }
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    title: "Hand-Thrown Terracotta Temple Urn with Flora Filigree",
    category: "Terracotta & Pottery",
    price: 1450,
    originalPrice: 1950,
    currency: "INR",
    stock: 9,
    artisanId: "artisan-1",
    artisanName: "Rameshwar Kumbhar",
    artisanAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
    artisanRegion: "Bishnupur, West Bengal",
    artisanStory: "Crafted on a traditional wooden potter wheel using holy alluvial clay from the banks of the Dwarakeswar river. Fired in an underground wood kiln for 18 hours to achieve deep rustic terracotta patina.",
    technique: "Wheel Throwing & Wood Kiln Terracotta Firing",
    materials: ["Alluvial River Clay", "Natural Red Oxide Slip", "Wood Ash Glaze"],
    images: [
      "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1200&q=80",
    ],
    primaryImage: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1200&q=80",
    rating: 4.9,
    reviewCount: 38,
    reviews: [
      {
        id: "rev-1",
        buyerName: "Ananya Sen",
        rating: 5,
        comment: "The earthy smell and exquisite carving are breathtaking. Arrived safely in zero-plastic rice husk cushioning!",
        date: "2 days ago",
        verifiedPurchase: true,
        craftsmanshipScore: 5,
        authenticityScore: 5,
      },
      {
        id: "rev-2",
        buyerName: "Marcus Vance",
        rating: 5,
        comment: "Direct artisan transparency is wonderful. Knowing Rameshwar-ji received 80% of the price makes this so special.",
        date: "1 week ago",
        verifiedPurchase: true,
      },
    ],
    dimensions: "32 cm (H) x 20 cm (W)",
    weight: "1.4 kg",
    tags: ["terracotta", "pottery", "handcrafted", "fair-trade", "bengal-craft", "eco-friendly"],
    craftBadge: "GI Tag Protected Style • Direct Guild",
    isVerified: true,
    createdDate: "2026-08-15",
    pricingBreakdown: {
      materialCost: 320,
      laborCost: 680,
      artisanFairMargin: 350,
      packagingShipping: 100,
      explanation: "Includes 12 hours of manual sculpting and kiln supervision at fair wage standards.",
    },
    marketPriceRange: {
      min: 1200,
      max: 2400,
      averageRetail: 1850,
    },
    careInstructions: [
      "Dust gently with a dry cotton cloth",
      "Wipe with damp cloth without chemical detergents",
      "Safe for indoor planters or dry flower arrangements",
    ],
    regionalTitles: {
      hi: "पारंपरिक हस्तनिर्मित टेराकोटा कलश व पुष्प नक्काशी",
      bn: "ঐতিহ্যবাহী বিষ্ণুপুরী পোড়ামাটির সুদৃশ্য কলসী",
      ta: "பாரம்பரிய சுடுமண் கலசம்",
    },
  },
  {
    id: "prod-2",
    title: "Ancient Dokra Lost-Wax Bell Metal Elephant Trio",
    category: "Dokra Metal Casting",
    price: 2650,
    originalPrice: 3400,
    currency: "INR",
    stock: 4,
    artisanId: "artisan-2",
    artisanName: "Mangala Devi Jhala",
    artisanAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80",
    artisanRegion: "Bastar, Chhattisgarh",
    artisanStory: "Preserving 4,000 years of tribal lost-wax metallurgy. Each elephant figurine is individually sculpted from hand-rolled beeswax threads over a clay core, melted in fire, and cast in molten bronze/brass.",
    technique: "4000-Year-Old Cire Perdue (Lost-Wax) Metal Casting",
    materials: ["Recycled Brass & Bronze", "Natural Beeswax", "Riverbed Soil", "Rice Husk Charcoal"],
    images: [
      "https://images.unsplash.com/photo-1606744824163-985d376605aa?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1590736969955-71cc94801759?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80",
    ],
    primaryImage: "https://images.unsplash.com/photo-1606744824163-985d376605aa?auto=format&fit=crop&w=1200&q=80",
    rating: 5.0,
    reviewCount: 42,
    reviews: [
      {
        id: "rev-3",
        buyerName: "Pooja Hegde",
        rating: 5,
        comment: "Pure tribal soul in metal. The intricate wire filigree and heavy solid feel are unmatched.",
        date: "3 days ago",
        verifiedPurchase: true,
      },
    ],
    dimensions: "Set of 3: 16cm, 12cm, 8cm (H)",
    weight: "2.1 kg total",
    tags: ["dokra", "tribal-metal", "brass", "lost-wax", "bastar-art", "collectible"],
    craftBadge: "Heritage Tribal Craft • 100% One-of-a-Kind",
    isVerified: true,
    createdDate: "2026-08-10",
    pricingBreakdown: {
      materialCost: 750,
      laborCost: 1100,
      artisanFairMargin: 600,
      packagingShipping: 200,
      explanation: "Single wax master mold created per piece; wax is destroyed during metal pouring.",
    },
    marketPriceRange: {
      min: 2400,
      max: 4500,
      averageRetail: 3600,
    },
    careInstructions: [
      "Wipe with dry microfiber cloth",
      "Apply slight drop of coconut oil annually to enrich brass glow",
    ],
    regionalTitles: {
      hi: "बस्तर ढोकरा ढलवां धातु हाथी समूह",
      bn: "প্রাচীন ডোকরা ধাতব হাতি ত্রয়ী",
    },
  },
  {
    id: "prod-3",
    title: "Original Madhubani Tree of Life & Forest Fauna Canvas",
    category: "Madhubani & Folk Painting",
    price: 3200,
    originalPrice: 4200,
    currency: "INR",
    stock: 3,
    artisanId: "artisan-3",
    artisanName: "Sunita & Radhey Mohan",
    artisanAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    artisanRegion: "Mithila, Bihar",
    artisanStory: "Painted with fine bamboo twigs and nibs using hand-extracted pigments: deep yellow from turmeric, black from lamp soot, blue from wild indigo, and green from broad bean leaves.",
    technique: "Freehand Kachni (Line Drawing) & Bharni (Color Fill)",
    materials: ["Handmade 300 GSM Cotton Paper", "Turmeric Pigment", "Indigo Dyes", "Neem Gum Binder"],
    images: [
      "https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=80",
    ],
    primaryImage: "https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1200&q=80",
    rating: 4.92,
    reviewCount: 29,
    reviews: [
      {
        id: "rev-4",
        buyerName: "Dr. Vikram Seth",
        rating: 5,
        comment: "Museum quality art! The micro-detail in the bird feathers and root knots is unbelievable.",
        date: "5 days ago",
        verifiedPurchase: true,
      },
    ],
    dimensions: "45 cm x 60 cm (Unframed Canvas)",
    weight: "180 g",
    tags: ["madhubani", "mithila", "folk-art", "natural-dyes", "wall-decor", "bihar"],
    craftBadge: "UNESCO Recognized Master Style",
    isVerified: true,
    createdDate: "2026-08-20",
    pricingBreakdown: {
      materialCost: 550,
      laborCost: 1650,
      artisanFairMargin: 800,
      packagingShipping: 200,
      explanation: "Required 28 continuous hours of micro-line freehand artwork without stencils.",
    },
    marketPriceRange: {
      min: 2900,
      max: 5500,
      averageRetail: 4200,
    },
    careInstructions: [
      "Keep framed behind non-reflective glass",
      "Avoid direct direct sunlight exposure to protect natural organic pigments",
    ],
  },
  {
    id: "prod-4",
    title: "Pure Handloom Pochampally Double Ikat Silk Stole",
    category: "Handloom & Textiles",
    price: 4500,
    originalPrice: 5800,
    currency: "INR",
    stock: 5,
    artisanId: "artisan-4",
    artisanName: "Kalyan Weavers Cooperative",
    artisanAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    artisanRegion: "Pochampally, Telangana",
    artisanStory: "Double Ikat is one of the most mathematically intricate weaving crafts in the world, where warp and weft yarns are tied and dyed separately with microscopic alignment before hand-weaving.",
    technique: "Traditional Wooden Pit Loom Double Ikat Weaving",
    materials: ["100% Mulberry Raw Silk", "Vegetable Madder & Indigo Dyes", "Zari Borders"],
    images: [
      "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=80",
    ],
    primaryImage: "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&w=1200&q=80",
    rating: 4.96,
    reviewCount: 51,
    reviews: [
      {
        id: "rev-5",
        buyerName: "Meenakshi Raman",
        rating: 5,
        comment: "Softest natural silk drape with sharp geometric chevron patterns. Truly proud of Indian handloom!",
        date: "4 days ago",
        verifiedPurchase: true,
      },
    ],
    dimensions: "200 cm (L) x 65 cm (W)",
    weight: "220 g",
    tags: ["silk", "handloom", "ikat", "pochampally", "sustainable-fashion", "organic"],
    craftBadge: "Silk Mark & Handloom Mark Certified",
    isVerified: true,
    createdDate: "2026-08-12",
    pricingBreakdown: {
      materialCost: 1600,
      laborCost: 1900,
      artisanFairMargin: 800,
      packagingShipping: 200,
      explanation: "Woven across 14 days on traditional family pit-looms with zero electric automation.",
    },
    marketPriceRange: {
      min: 4200,
      max: 7500,
      averageRetail: 5900,
    },
    careInstructions: [
      "Dry clean only for initial washes",
      "Iron on low silk heat with protective cloth",
    ],
  },
  {
    id: "prod-5",
    title: "Hand-Carved Saharanpur Rosewood Intricate Jali Box",
    category: "Woodcarving & Crafts",
    price: 1850,
    originalPrice: 2400,
    currency: "INR",
    stock: 8,
    artisanId: "artisan-1",
    artisanName: "Rameshwar Kumbhar",
    artisanAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
    artisanRegion: "Saharanpur & Cluster",
    artisanStory: "Chiseled from ethically salvaged Sheesham rosewood with openwork floral latticework (Jali) and brass inlay pins.",
    technique: "Tarkashi Metal Wire & Chisel Openwork Jali",
    materials: ["Certified Seasoned Sheesham Wood", "Brass Wire Inlay", "Beeswax Polish"],
    images: [
      "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1546484396-fb3fc6f95f98?auto=format&fit=crop&w=1200&q=80",
    ],
    primaryImage: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1200&q=80",
    rating: 4.88,
    reviewCount: 22,
    reviews: [],
    dimensions: "20 cm x 12 cm x 8 cm",
    weight: "650 g",
    tags: ["woodcraft", "jali", "rosewood", "tarkashi", "keepsake"],
    craftBadge: "Sustainable Forestry Certified",
    isVerified: true,
    createdDate: "2026-08-18",
    pricingBreakdown: {
      materialCost: 450,
      laborCost: 850,
      artisanFairMargin: 450,
      packagingShipping: 100,
      explanation: "Precision hand chisel carving with natural non-toxic oil buff.",
    },
    marketPriceRange: {
      min: 1600,
      max: 2800,
      averageRetail: 2200,
    },
    careInstructions: ["Condition with natural wood wax once every 6 months"],
  },
  {
    id: "prod-6",
    title: "Jaipur Hand-Turned Quartz Blue Pottery Floral Vase",
    category: "Terracotta & Pottery",
    price: 1950,
    originalPrice: 2500,
    currency: "INR",
    stock: 6,
    artisanId: "artisan-1",
    artisanName: "Rameshwar Kumbhar",
    artisanAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
    artisanRegion: "Rajasthan Artisans Guild",
    artisanStory: "Traditional clay-free blue pottery made using ground quartz stone powder, Fuller's earth, and katira gum glazed with copper oxide turquoise pigments.",
    technique: "Quartz Stone Dough Low-Fire Kiln Glazing",
    materials: ["Quartz Powder", "Natural Glass Frit", "Copper Oxide Turqoise Pigment"],
    images: [
      "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&w=1200&q=80",
    ],
    primaryImage: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1200&q=80",
    rating: 4.85,
    reviewCount: 17,
    reviews: [],
    dimensions: "24 cm (H) x 14 cm (Dia)",
    weight: "920 g",
    tags: ["blue-pottery", "jaipur", "quartz", "turquoise", "heritage"],
    craftBadge: "Authentic GI Craft Certified",
    isVerified: true,
    createdDate: "2026-08-22",
    pricingBreakdown: {
      materialCost: 480,
      laborCost: 920,
      artisanFairMargin: 450,
      packagingShipping: 100,
      explanation: "Fired in low-temperature wood kilns; hand painted with cobalt floral arabesques.",
    },
    marketPriceRange: {
      min: 1700,
      max: 3000,
      averageRetail: 2400,
    },
    careInstructions: ["Clean with lukewarm water; do not put in dishwasher"],
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: "ORD-8492-IN",
    items: [
      {
        product: INITIAL_PRODUCTS[0],
        quantity: 1,
      },
      {
        product: INITIAL_PRODUCTS[1],
        quantity: 1,
      },
    ],
    subtotal: 4100,
    shippingFee: 0,
    fairTradeContribution: 205,
    tax: 120,
    totalAmount: 4425,
    currency: "INR",
    buyerName: "Priyanka Roy",
    buyerEmail: "priyanka.roy@craftlove.in",
    buyerPhone: "+91 98200 45610",
    shippingAddress: {
      street: "Flat 402, Green Meadows, Indiranagar",
      city: "Bengaluru",
      state: "Karnataka",
      zipCode: "560038",
      country: "India",
    },
    paymentMethod: "upi",
    paymentStatus: "paid",
    orderStatus: "dispatched",
    trackingNumber: "IND-POST-789042",
    courierName: "India Post Rural SpeedPost (Eco-Insured)",
    placedAt: "2026-08-25T14:30:00Z",
    estimatedDelivery: "2026-08-30",
    timeline: [
      {
        status: "placed",
        timestamp: "2026-08-25T14:30:00Z",
        note: "Order confirmed with instant fair-wage escrow allocation",
      },
      {
        status: "confirmed",
        timestamp: "2026-08-25T15:10:00Z",
        note: "Artisan Rameshwar Kumbhar verified craft readiness",
      },
      {
        status: "crafting",
        timestamp: "2026-08-26T10:00:00Z",
        note: "Items inspected & packed in biodegradable banana-fiber padding",
      },
      {
        status: "dispatched",
        timestamp: "2026-08-26T17:40:00Z",
        note: "Dispatched from Bishnupur Rural Postal Hub via SpeedPost",
      },
    ],
    artisanIds: ["artisan-1", "artisan-2"],
  },
  {
    id: "ORD-7319-IN",
    items: [
      {
        product: INITIAL_PRODUCTS[2],
        quantity: 1,
      },
    ],
    subtotal: 3200,
    shippingFee: 0,
    fairTradeContribution: 160,
    tax: 95,
    totalAmount: 3455,
    currency: "INR",
    buyerName: "Rohan Varma",
    buyerEmail: "rohan.varma@heritage.org",
    buyerPhone: "+91 99881 12345",
    shippingAddress: {
      street: "House 12, Civil Lines",
      city: "Jaipur",
      state: "Rajasthan",
      zipCode: "302006",
      country: "India",
    },
    paymentMethod: "card",
    paymentStatus: "paid",
    orderStatus: "crafting",
    trackingNumber: "EXP-CRAFT-55209",
    courierName: "BlueDart Artisan Express",
    placedAt: "2026-08-26T09:15:00Z",
    estimatedDelivery: "2026-09-02",
    timeline: [
      {
        status: "placed",
        timestamp: "2026-08-26T09:15:00Z",
        note: "Order received and validated",
      },
      {
        status: "confirmed",
        timestamp: "2026-08-26T11:00:00Z",
        note: "Artisan Sunita Devi began custom archival framing wrap",
      },
      {
        status: "crafting",
        timestamp: "2026-08-27T08:00:00Z",
        note: "Final natural lacquer varnish coat curing",
      },
    ],
    artisanIds: ["artisan-3"],
  },
];

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: "conv-1",
    buyerId: "buyer-priyanka",
    buyerName: "Priyanka Roy",
    artisanId: "artisan-1",
    artisanName: "Rameshwar Kumbhar",
    productId: "prod-1",
    lastMessage: "Thank you! I have packed the urn with thick rice-straw protection and it is already dispatched via SpeedPost.",
    lastMessageTime: "10 mins ago",
    unreadCount: 1,
  },
  {
    id: "conv-2",
    buyerId: "buyer-priyanka",
    buyerName: "Priyanka Roy",
    artisanId: "artisan-2",
    artisanName: "Mangala Devi Jhala",
    productId: "prod-2",
    lastMessage: "Yes, I can cast an elephant pair with custom tribal motifs if you like!",
    lastMessageTime: "Yesterday",
    unreadCount: 0,
  },
  {
    id: "conv-3",
    buyerId: "buyer-priyanka",
    buyerName: "Priyanka Roy",
    artisanId: "artisan-3",
    artisanName: "Sunita & Radhey Mohan",
    productId: "prod-3",
    lastMessage: "नमस्ते! हम इस पेंटिंग को प्राकृतिक हल्दी और नील के रंगों से पूरा कर रहे हैं।",
    lastMessageTime: "2 days ago",
    unreadCount: 0,
  },
  {
    id: "conv-4",
    buyerId: "buyer-priyanka",
    buyerName: "Priyanka Roy",
    artisanId: "artisan-4",
    artisanName: "Kalyan Weavers Co-operative",
    productId: "prod-4",
    lastMessage: "The natural wild tussar silk stole has been woven on our generational pit loom.",
    lastMessageTime: "3 days ago",
    unreadCount: 0,
  },
];

export const INITIAL_MESSAGES: ChatMessage[] = [
  {
    id: "msg-1",
    conversationId: "conv-1",
    senderId: "buyer-priyanka",
    senderName: "Priyanka Roy",
    senderRole: "buyer",
    text: "Hello Rameshwar-ji, can this terracotta urn withstand monsoon humidity on a covered balcony?",
    originalLanguage: "en",
    timestamp: "Yesterday, 4:15 PM",
    productId: "prod-1",
    productSnapshot: {
      id: "prod-1",
      title: "Hand-Thrown Terracotta Temple Urn",
      image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=400&q=80",
      price: 1450,
    },
  },
  {
    id: "msg-2",
    conversationId: "conv-1",
    senderId: "artisan-1",
    senderName: "Rameshwar Kumbhar",
    senderRole: "artisan",
    text: "नमस्ते! हाँ, यह उच्च तापमान वाली भट्टी में 18 घंटे पकाया गया है। यह बारिश और नमी दोनों में बिल्कुल सुरक्षित रहता है।",
    originalLanguage: "hi",
    translatedText: "Namaste! Yes, this was baked in high-temperature wood kilns for 18 hours. It is completely safe in humidity and mild rain.",
    targetLanguage: "en",
    timestamp: "Yesterday, 4:45 PM",
    suggestedFollowups: [
      "How should I clean and maintain it?",
      "Can you customize dimensions for a garden corner?",
      "What packaging do you use for fragile terracotta?",
    ],
  },
  {
    id: "msg-3",
    conversationId: "conv-1",
    senderId: "artisan-1",
    senderName: "Rameshwar Kumbhar",
    senderRole: "artisan",
    text: "Thank you! I have packed the urn with thick rice-straw protection and it is already dispatched via SpeedPost.",
    originalLanguage: "en",
    timestamp: "10 mins ago",
  },
  {
    id: "msg-4",
    conversationId: "conv-2",
    senderId: "buyer-priyanka",
    senderName: "Priyanka Roy",
    senderRole: "buyer",
    text: "Mangala Devi-ji, could you make a customized brass Dokra elephant with traditional Chhattisgarh sun motifs?",
    originalLanguage: "en",
    timestamp: "Yesterday, 11:30 AM",
    productId: "prod-2",
    productSnapshot: {
      id: "prod-2",
      title: "Dokra Lost-Wax Bell Metal Elephant Trio",
      image: "https://images.unsplash.com/photo-1590736969955-71cc94801759?auto=format&fit=crop&w=400&q=80",
      price: 1950,
    },
  },
  {
    id: "msg-5",
    conversationId: "conv-2",
    senderId: "artisan-2",
    senderName: "Mangala Devi Jhala",
    senderRole: "artisan",
    text: "नमस्ते! हाँ, हम मधुमक्खी के मोम से नया सांचा बनाकर सूर्य और मोर का डिज़ाइन 4 दिनों में ढाल देंगे।",
    originalLanguage: "hi",
    translatedText: "Namaste! Yes, I will hand-sculpt a new beeswax matrix with sun and peacock tribal motifs within 4 days.",
    targetLanguage: "en",
    timestamp: "Yesterday, 1:20 PM",
    suggestedFollowups: [
      "Will you share a photo before shipping?",
      "What is the total weight with packaging?",
      "Can you add a custom dedication tag?",
    ],
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: "notif-1",
    title: "Order Dispatched! 📦",
    message: "Your handcrafted Terracotta Urn has left Bishnupur Hub. Tracking: IND-POST-789042",
    type: "order",
    read: false,
    timestamp: "Just now",
    linkTab: "buyer_orders",
    orderId: "ORD-8492-IN",
  },
  {
    id: "notif-2",
    title: "New Buyer Inquiry 💬",
    message: "Priyanka sent a message regarding custom terracotta dimensions.",
    type: "message",
    read: false,
    timestamp: "15 mins ago",
    linkTab: "messages",
  },
  {
    id: "notif-3",
    title: "Fair-Wage Payout Cleared 💰",
    message: "₹3,750 directly deposited to Kumbhakar Co-Op Bank Account #...8921.",
    type: "payout",
    read: true,
    timestamp: "Yesterday",
    linkTab: "seller_orders",
  },
  {
    id: "notif-4",
    title: "Low Stock Alert ⚠️",
    message: "Dokra Lost-Wax Bell Metal Elephant Trio has only 4 pieces remaining in stock.",
    type: "stock",
    read: true,
    timestamp: "2 days ago",
    linkTab: "seller_orders",
  },
];
